# Railway deployment configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "hypercorn app.main:app --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
DATABASE_URL = "sqlite:///./app.db"
