# Railway deployment configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "hypercorn app.main:app --bind \"[::]:$PORT\'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
DATABASE_URL = "sqlite:///./app.db"
